### ISSUE TITLE
Consulta situação do Título

### ISSUE THREAD

**Issue by jfsts** [renatojdev/bancointer-python#3]
Quando estou fazendo a consulta, utilizando do modelo de exemplo, coloco o número do título mas está dando o erro abaixo:
Traceback (most recent call last):
  File "C:\Users\Jefferson\PycharmProjects\NOVOPOST\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Jefferson\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jefferson\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jefferson\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jefferson\PycharmProjects\NOVOPOST\comunidadeimpressionadora\consultaboleto.py", line 22, in <module>
    response = bi.consulta(nosso_numero="00921421196")
  File "C:\Users\Jefferson\PycharmProjects\NOVOPOST\comunidadeimpressionadora\bancointer.py", line 375, in consulta
    return response.json()
  File "C:\Users\Jefferson\PycharmProjects\NOVOPOST\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

O que poderia ser ?

**Comment by renatojdev** [comment]
Verifique as as configurações do seu projeto de implementação que usa a biblioteca, arquivo `.env` se está tudo OK principalmente o path das chaves do certificado que baixou do Banco. 
Tente também re-instalar o projeto fora do pycharm, crie um enviroment venv para o projeto e execute os testes novamente.

**Comment by jfsts** [comment]
Obrigado Renato.
Consegui resolver.
Valeu pela atenção amigo.

Jefferson 

Enviado do Yahoo Mail no Android 
 
  Em qua., 8 8e fev. 8e 2023 às 7:04, Renato P. E. ***@***.***> escreveu:   


Closed #3 as not planned.
